
##########################################
#     Change these variables !important
##########################################

owner: 王鹏

title: 我的博客

# Set subtitle e.g "blog"
subtitle: 不积跬步 无以至千里

# Following needed for disqus integration

# Set your 'disqus' account name
disqus:

# Uncomment if deployed locally
# url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url:

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl:

# Change this to your google analytics ID
google_analytics:

# Change this to your http://getsimpleform.com public key
contact_PK:

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 30

##########################################
#          Do not change these variables
##########################################

include:  ["pages"]

sass:
  sass_dir: _sass
sass:
    style: compressed


gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file
  - jekyll-seo-tag # seo meta tag & json-ld
  - jekyll-feed # add /feed.xml file

paginate_path: /pages/page:num
