
##########################################
#     Change these variables !important
##########################################

owner: Name Surname

title: Aliquam

# Set subtitle e.g "blog"
subtitle: Theme

# Following needed for disqus integration

# Set your 'disqus' account name
disqus: grrinchas

# Uncomment if deployed locally
# url: http://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: https://www.dennis-grinch.co.uk

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl: /aliquam

# Change this to your google analytics ID
google_analytics:

contact_PK:

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 30

##########################################
#          Do not change these variables
##########################################

include:  ["pages"]

sass:
  sass_dir: _sass
sass:
    style: compressed


gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file
  - jekyll-seo-tag # seo meta tag & json-ld
  - jekyll-feed # add /feed.xml file

paginate_path: /pages/page:num
